import type { CrowdLevel, ServiceDef } from "./data";

/**
 * BheedLess waiting-time engine.
 * Numerical predictions are always computed from structured data —
 * never generated by a language model.
 *
 * Base formula:
 *   Estimated Wait = People Ahead x Average Service Time / Active Counters
 * Adjusted for crowd level, counter utilisation and time of day.
 */

export function crowdLevel(waiting: number): CrowdLevel {
  if (waiting >= 40) return "High";
  if (waiting >= 18) return "Medium";
  return "Low";
}

export function timeOfDayFactor(date = new Date()): number {
  const h = date.getHours() + date.getMinutes() / 60;
  if (h >= 11 && h < 13.5) return 1.18; // peak window
  if (h >= 9.5 && h < 11) return 1.06;
  if (h >= 16) return 0.9;
  return 1;
}

export function crowdFactor(level: CrowdLevel): number {
  return level === "High" ? 1.15 : level === "Medium" ? 1.05 : 0.95;
}

export interface Prediction {
  minutes: number;
  confidence: number;
  level: CrowdLevel;
  factors: { label: string; value: string }[];
}

export function predictWait(
  service: ServiceDef,
  peopleAhead = service.waiting,
  now = new Date(),
): Prediction {
  const active = Math.max(1, service.activeCounters);
  const level = crowdLevel(service.waiting);
  const base = (peopleAhead * service.avgServiceTime) / active;
  const utilisation = service.activeCounters / service.counters;
  const utilisationPenalty = utilisation >= 1 ? 0.96 : 1 + (1 - utilisation) * 0.12;
  const minutes = Math.max(
    1,
    Math.round(base * crowdFactor(level) * timeOfDayFactor(now) * utilisationPenalty),
  );

  const confidence = Math.round(
    Math.min(97, 99 - Math.abs(peopleAhead - 20) * 0.12 - (level === "High" ? 4 : 0)),
  );

  return {
    minutes,
    confidence,
    level,
    factors: [
      { label: "People ahead", value: `${peopleAhead}` },
      { label: "Active counters", value: `${service.activeCounters} / ${service.counters}` },
      { label: "Average service time", value: `${service.avgServiceTime.toFixed(1)} min` },
      { label: "Current crowd", value: level },
      {
        label: "Historical demand",
        value: timeOfDayFactor(now) > 1.1 ? "Above normal" : "Normal",
      },
    ],
  };
}

export function forecastSeries(service: ServiceDef) {
  const labels = ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "1:00"];
  const shape = [0.78, 0.89, 1, 1.17, 1.5, 1.33, 1.05];
  const anchor = predictWait(service).minutes;
  return labels.map((time, i) => ({
    time,
    wait: Math.max(2, Math.round(anchor * (shape[i] as number))),
  }));
}

export function addMinutes(date: Date, minutes: number) {
  return new Date(date.getTime() + minutes * 60000);
}

export function formatTime(date: Date) {
  return date.toLocaleTimeString("en-IN", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}

export function formatDate(date: Date) {
  return date.toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

/** Minutes remaining until an appointment (ISO date + "HH:mm"). */
export function minutesUntil(dateISO: string, time24: string, now = new Date()) {
  const parts = time24.split(":");
  const target = new Date(dateISO);
  target.setHours(Number(parts[0] ?? 0), Number(parts[1] ?? 0), 0, 0);
  return (target.getTime() - now.getTime()) / 60000;
}

/** Strict rule: cancellation allowed only when MORE than 10 minutes remain. */
export const CANCEL_WINDOW_MINUTES = 10;
export function canCancel(dateISO: string, time24: string, now = new Date()) {
  return minutesUntil(dateISO, time24, now) > CANCEL_WINDOW_MINUTES;
}
